### ISSUE TITLE
Build with "travelling ruby"

### ISSUE THREAD

**Issue by koenpunt** [fastlane/packaged-fastlane#74]
To completely omit the Ruby requirement, it might be worth investigating if it's possible to ship it with a bundled ruby by means of Phusion's travelling ruby: https://github.com/phusion/traveling-ruby

**Comment by KrauseFx** [comment]
We actually looked into this, and there were some reasons why we didn't go ahead with it. I can't remember, maybe @ohwutup does? 👍

**Comment by ohwutup** [comment]
I don't remember exactly the reasons for not going with that solution, but IIRC, I think they weren't going to be maintaining it for very long and it was a much more complicated solution to building a packaged up ruby environment. That being said, I would be curious what advantage it would have over our current approach. @koenpunt, IIRC traveling ruby does something similar to what we are doing no?

**Comment by KrauseFx** [comment]
Right, it uses hosted Ruby zip files that we couldn't build ourselves in the future when something breaks.

**Comment by ohwutup** [comment]
Going to close this for now, happy to keep conversation going though @koenpunt !
