### ISSUE TITLE
Packaged version on fastlane.tools/fastlane.zip is outdated

### ISSUE THREAD

**Issue by SMillerDev** [fastlane/packaged-fastlane#96]
The hosted packaged version hasn't been updated in a long time. I'd think a bump should be part of every fastlane release.

**Comment by KrauseFx** [comment]
@joshdholtz @snatchev can say more, but from what I remember, we can't actually build a new one, as it has to run on a really old macOS, similar to what CocoaPods does. So the way we solved it back in the days, to run a `bundle update`, automatically after installing fastlane. So the `bundle update` might take a little longer, but it should work. Does it?

**Comment by snatchev** [comment]
@KrauseFx I'll circle back with @joshdholtz. Honestly, I didn't know this project existed. We might have to evaluate its long term usefulness, especially if it is not well supported.

**Comment by ohayon** [comment]
I had made this a long while back when we wanted to put it in the Fabric mac app. Hasn't been touched in quite some time, but I know a couple of folks that rely on it.

**Comment by SMillerDev** [comment]
Anyone who uses homebrew to install fastlane sorta relies on it.

**Comment by ohayon** [comment]
Yeah, definitely. And apologies that it's not getting proper maintenance these days. I'll defer to @snatchev and @joshdholtz about how we want to handle this moving forward.

**Comment by joshdholtz** [comment]
I'm fixing 🙃 Building rubies just takes time 💤 

❤️s for @ohayon for the initial work on this!

**Comment by joshdholtz** [comment]
But also, this doesn't actually need bumping for every version of _fastlane_. It will self update but there is an issue were its locked at an older version of _fastlane_ due to this running on Ruby 2.2 so working on bumping this to work with Ruby 2.4 😇

**Comment by SMillerDev** [comment]
Purely from a user standpoint I would expect an official download from the official website to have the same behavior as running a gem install. Even if it might not be needed to bump for every version I'd say that it is the least surprising behavior.

**Comment by joshdholtz** [comment]
@SMillerDev Closing this since this is now migrated to a new formula (which I believe you were part of that PR 😊 )

https://github.com/Homebrew/homebrew-core/pull/47709

**Comment by SMillerDev** [comment]
I was, thanks for the work. I bet this makes things easier on fastlane too.
